language: ruby
rvm:
- 2.0.0
sudo: false
env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
before_deploy: "rake gemspec"
deploy:
  provider: rubygems
  api_key:
    secure: fnOp3A3WonrHGv7W+mhjaoFjgpZF6XsqaI1z+MoHPoi/BX9a7Nl1nOXTnn18KoIBB9L7tYQHGWVEWwam6MFYoSqOSIBP6+LPZ4bam6T7EUHHNykN3LEFBrruUruWncFKcKWv+daopT+AX5hCohlv+ajaaxG+J2lpGziyaVXVwXxW944apgsl03BNr+PvaSLJqRhYXFUTwVYaSRO3NeHkVUn5ZD2cP9HXCYW3xvlTo/fNG4eTXEDKzBt8OhiMX6W6f/jMCpneefrf5qJH8SzegmbI7hhAVpKcUwMsu/P9ecnsgJCWo/lJ4vDdz9qBSgeTTJIBM1ClVivSo+dfDja0bChfzPtFyHSQYOwdVRQNQtX2u0QhhdPSDKP3RZbCCKjrhbjCcJVMAPwkiHLTAzVsRMIUt1AV6z5OZ1hPNYVxzSD97ee1f7M2UWvd4iCkHl/oHwwIdfsJ4Bn89XbjGaN4+vgyoYvUkGJy8+yQ5wTscB2yqnCwKkzxAi/ZhYWjLKskxYIBiMhqHeaMl9yUevqCTSpWlDfbk+chI28gzNS9XoCrefLSIs+W7U6Bs6l+WuZgJ8jTMeb+dFWFae7l2K87g++1hVXohdcqo1dspl4cN4JbL8GX89XlqlPgyI7Bfu/w2cLFyDQ1igfQDRrIx/IGQMVYhsMnb4Gof+402H1Gcc4=
  gem: totally_lazy
  on:
    repo: raymanoz/totally_lazy
