require_relative 'totally_lazy/comparators'
require_relative 'totally_lazy/either'
require_relative 'totally_lazy/enumerators'
require_relative 'totally_lazy/functions'
require_relative 'totally_lazy/maps'
require_relative 'totally_lazy/numbers'
require_relative 'totally_lazy/option'
require_relative 'totally_lazy/pair'
require_relative 'totally_lazy/predicates'
require_relative 'totally_lazy/sequence'
require_relative 'totally_lazy/strings'

include Comparators
include Eithers
include Enumerators
include Functions
include Maps
include Numbers
include Options
include Pairs
include Predicates
include Sequences
include Strings
