require_relative 'comparators'
require_relative 'enumerators'
require_relative 'functions'
require_relative 'numbers'
require_relative 'option'
require_relative 'pair'
require_relative 'predicates'
require_relative 'sequence'
require_relative 'strings'

include Comparators
include Enumerators
include Functions
include Numbers
include Option
include Pair
include Predicates
include Sequences
include Strings